services:
  redis:
    image: redis
    container_name: ecommerce_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - ecommerce_net

  db:
    image: postgres
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ecommerce_net

networks:
  ecommerce_net:

volumes:
  db_data:
  redis_data:
